### ISSUE TITLE
Long titles

### ISSUE THREAD

**Issue by AlterOld** [OleksiyPenkov/MyHomeLib#10]
Спасибо, с просмотром всё работает отлично. Осталась проблема с сохранением на устройство: MyHomeLib безо всяких сообщений тихо не создаёт файл, у которого длинный путь. В итоге пользователь даже не знает, что выбранная книга у него отсутствует.
И есть ещё одна неприятность (пример BookID 291311 и 299719): название может быть одинаковым до самого последнего символа, в данном случае - "Рузвельт Франклин, Сталин Иосиф Виссарионович, Черчилль Уинстон Спенсер. Переписка Председателя Совета Министров СССР с Президентами США и Премьер-Министрами Великобритании во время Великой Отечественной войны 1941–1945 гг. Том 1" или "...Том 2". Серии нет, номера в серии тоже нет.
Ещё раз спасибо.

**Comment by OleksiyPenkov** [comment]
Понял, проверю.

**Comment by SlalomJohn** [comment]
Самое грустное, что просто так подрезать имя нельзя. Там есть отличия - типа том1 или том2 или еще какое чудное различие. И каждый раз оно разное...

**Comment by AlterOld** [comment]
Как по мне, самый простой способ - сохранять не под именем,  а под ID. Чуть-чуть сложнее, но намного информативнее - обрезать с запасом 6-7 символов и опять же добавлять ID. А так-то вариантов разных много, не мне решать.

**Comment by OleksiyPenkov** [comment]
Второй вариант мне тоже в голову пришел. Думаю, так и сделаю.

**Comment by OleksiyPenkov** [comment]
Поправил

**Comment by AlterOld** [comment]
Из 117 книг, для которых собственная длина пути (  %fc\%s + [%n_]%t  ) больше ~185 символов текущая версия не может сохранить 11. Строка запроса для имени файла:
=357842 or =746978 or =746979 or =746980 or =468118 or =468119 or =476558 or =442206 or =153487 or =646224 or =736048
При этом "читать" открываются все. Длина пути для 468118 - около 192 символов, для 736048 - 314.

Не знаю, важно ли это: в большинстве титлов (названий книг) для этих ID есть спецсимволы (?, ", :), кроме 476558, 736048 и 746978, но там длина титла соотв. 219, 240 и 228 символов.

Спасибо.

**Comment by OleksiyPenkov** [comment]
Поправил ещё раз )))

**Comment by AlterOld** [comment]
Круто.
Если я правильно понял, теперь по необходимости игнорируются все доп. папки (даже элементы папки назначения снизу вверх), зато книга будет сохранена.
Спасибо.
