### ISSUE TITLE
Ошибка в URL

### ISSUE THREAD

**Issue by alex80** [OleksiyPenkov/MyHomeLib#11]
Здравствуйте.
В строках 726, и 727 перед https стоит пробел. Из-за этого при запуске из архива MHL создает неправильный ini и не находит сервер с коллекциями.

https://github.com/OleksiyPenkov/MyHomeLib/blob/25bc431602f550cf50b1b24f49cb95de8fec662d/Program/Units/unit_Settings.pas#L726
https://github.com/OleksiyPenkov/MyHomeLib/blob/25bc431602f550cf50b1b24f49cb95de8fec662d/Program/Units/unit_Settings.pas#L727

ЗЫ. Благодарю за прекрасную программу!

**Comment by OleksiyPenkov** [comment]
Копипаста - зло )))

**Comment by OleksiyPenkov** [comment]
Fixed
