### ISSUE TITLE
Очищается таблица с книгами автора

### ISSUE THREAD

**Issue by z-alex68** [OleksiyPenkov/MyHomeLib#13]
Как смоделировать:
Выбрали автора в левой таблице.
В правой появился список книг.
В левой таблице делаем щелчек левой клавишей мыши по уже выбранному автору - спиок книг очистится.

Чтоб снова появились книги, нужно сместиться на другого автора.

**Comment by SlalomJohn** [comment]
На 2.3.4.832 аналогичное поведение.

**Comment by AlterOld** [comment]
Да, без перехода к другому автору помогает выбор языка, даже того же самого.

**Comment by OleksiyPenkov** [comment]
Поправил, обновил файл PRE 2.3.5
