### ISSUE TITLE
Неполная конвертация книг

### ISSUE THREAD

**Issue by NataliMi13** [OleksiyPenkov/MyHomeLib#15]
Когда конвертируешь книги в txt формат, то у некоторым обрезаются первые абзацы.

**Comment by OleksiyPenkov** [comment]
Конкретные примеры, пожалуйста. Лучше всего прикрепить проблемные fb2 файлы здесь.

**Comment by NataliMi13** [comment]
Исходный fb2
[02 - Король изумрудов.fb2.zip](https://github.com/OleksiyPenkov/MyHomeLib/files/10897475/02.-.fb2.zip)

И вот конвертированный в txt 
[02 - Король изумрудов.txt](https://github.com/OleksiyPenkov/MyHomeLib/files/10897481/02.-.txt)

**Comment by NataliMi13** [comment]
И так пропадает каждый первый абзац в начале глав и в самой главе, если текст идет с небольшим отступом между абзацами.

**Comment by NataliMi13** [comment]
И вот еще пример,
[Агробление по-олбански.fb2.zip](https://github.com/OleksiyPenkov/MyHomeLib/files/10897518/-.fb2.zip)

[Агробление по-олбански.txt](https://github.com/OleksiyPenkov/MyHomeLib/files/10897521/-.txt)

**Comment by OleksiyPenkov** [comment]
Исправил

**Comment by NataliMi13** [comment]
> Исправил

Подскажите, пожалуйста, как мне установить это и все другие исправления себе?

**Comment by NataliMi13** [comment]
Спасибо
