### ISSUE TITLE
Вопрос по жанрам

### ISSUE THREAD

**Issue by SlalomJohn** [OleksiyPenkov/MyHomeLib#16]
Собственно, жанры были поправлены в меру разумения.
Но не помешает проверить на всякий случай.
Имеется ввиду genres_fb2.glst
genres_nonfb2.glst не трогал вообще.
[genres_fb2.zip](https://github.com/OleksiyPenkov/MyHomeLib/files/10919353/genres_fb2.zip)

**Comment by OleksiyPenkov** [comment]
Вроде нормально все.

**Comment by OleksiyPenkov** [comment]
Кстати. Можно восстановить автоматическое обновление online. Достаточно закидывать inpx сюда https://github.com/OleksiyPenkov/oleksiypenkov.github.io
Могу добавить тебя в контрибьюторы

**Comment by SlalomJohn** [comment]
Ну в принципе можно. Если будет внятная инструкция как именно там все устроено. Я помню, что там в двух местах надо делать и вроде еще файл версии?

**Comment by OleksiyPenkov** [comment]
Да, я набросаю инструкцию.
