### ISSUE TITLE
Build instruction needed

### ISSUE THREAD

**Issue by AndriiZ** [OleksiyPenkov/MyHomeLib#17]
Hi,

Do you have an instruction on how to build MyHomeLib? It would be really helpful for newbies or oldies to make any improvements. 

First of all, IDE version and setup configuration is needed. 

Another question, any extra packages required for a successful build

**Comment by OleksiyPenkov** [comment]
0. Prerequisites: Delphi 11 Alexandria. FastMM5
1. Open Program/MHL.groupproj
2. Build and install MHL components
