### ISSUE TITLE
 Новая пустая коллекция в x64

### ISSUE THREAD

**Issue by OleksiyPenkov** [OleksiyPenkov/MyHomeLib#21]
В х64 невозможно создать пустую коллекцию. Мастер не переходит на следующую страницу.

**Comment by SlalomJohn** [comment]
Кстати - что за кипиш с Украинскими вставками и флагами? И аккаунт на буктрекере твой заблочили походу....

**Comment by OleksiyPenkov** [comment]
Долбоебы, сэр.

**Comment by SlalomJohn** [comment]
А с майнером что за прикол? Я так понял - в основной ветке он появился тоже...

**Comment by OleksiyPenkov** [comment]
`А с майнером что за прикол? Я так понял - в основной ветке он появился `тоже...`
Что, кто-то ещё испужался? Самосбывающееся пророчество )))
 Из той же серии, что и секретная функция.
 Вообще, наличие в папке какого-либо файла совершенно не означает, что он где-то используется. Он может быть даже не подключен к проекту, и, соответственно, не компилируется. Что и имеет место быть в случае секретной функции и майнера.
"Майнер" тот  вообще не может быть в принципе скомпилирован потому что это кривой интерфейс сгенерированный ChatGPT )))

**Comment by OleksiyPenkov** [comment]
Я не могу запретить альтернативо одаренным существам пользоватья моей программой. Зато могу сделать так, что бы они сами перестали, в силу своей альтернативности )))

**Comment by enzain** [comment]
Альтернативно-одаренные могут скачать исходники и убрать всю ......ю оттуда... и продолжать пользоваться.... 
Но жаль, что приходится этим заниматься... ))

**Comment by OleksiyPenkov** [comment]
Обычно у них на это мозга не хватает.
К тому же скачивание приводит к появлению на локальном диске зашифрованной фразы "Слава Украине", что для них равносильно вызову дьявола ))) Ну и уголовная статья автоматически. Или даже две )))

**Comment by OleksiyPenkov** [comment]
Чуваки на буктрекере продолжают демонстрировать свою альтернативность. Вирусы, вон нашли. В Алридере. И даже никакой мысли в голове не возникло.
Я одного не понимаю, зачем они продолжают грызть кактус? Ну и пользовались бы своим Либруслибом, прости господи. Или любым   форком. Так нет, "полечил" файлы доктором вебом. Ню-ню.

**Comment by SlalomJohn** [comment]
Я уже запарился там объяснять, что он сам не знает, что хочет и вообще.
У него антивирь бета со старыми базами что-то там находит (и даже лечит!) и как ни странно - после лечения все работает.
Возникает вопрос - откуда у него в файлах появились вирусы :D

**Comment by OleksiyPenkov** [comment]
Это не вирусы, это ложное срабатывание на компилятор. Время от времени такое происходит. Типа какая-то сигнатура которая встречалась в настоящей малвари написанной на Дельфях. Нормальные антивирусы на это не ведутся.

**Comment by SlalomJohn** [comment]
Там даже не на компилятор, просто сигнатуры не допиляны в старых базах.
В новых все тип-топ...
И от антивируса это не зависит - просто когда находят такой ложняк - просто правят детект на более кошерный :)

**Comment by SlalomJohn** [comment]
Кстати - пытаюсь скомпилить из сырцов - у меня куча ошибок на Virtual-TreeView
а FastMM5 я нашел
Embarcadero® Delphi 11 Version 28.0.47991.2819
