### ISSUE TITLE
Код - непонятно что это

### ISSUE THREAD

**Issue by SlalomJohn** [OleksiyPenkov/MyHomeLib#27]
собственно в **MHL.groupproj**
указано - 
..\..\..\..\Profile\Documents\Embarcadero\Studio\Projects\MHL.dproj

но такого проекта нет. Видать поэтому глючит компиляцию, если не добавить папку с компонентами в настройках путей

**Comment by SlalomJohn** [comment]
Кстати - я себе форк запилил, внес небольшие правки в код инсталлера и так по мелочи.
Плюс пересобрал структуру инсталлера по папкам - для x64 оставил только DLL и EXE - остальное из x32 версии берется что более верно.
Посмотри - возможно будет полезно для дальнейшего использования.

**Comment by OleksiyPenkov** [comment]
> собственно в **MHL.groupproj** указано - ........\Profile\Documents\Embarcadero\Studio\Projects\MHL.dproj
> 
> но такого проекта нет. Видать поэтому глючит компиляцию, если не добавить папку с компонентами в настройках путей

Какое-то древнее легаси, видимо.

**Comment by OleksiyPenkov** [comment]
Не воспроизводится
