### ISSUE TITLE
Иероглифы

### ISSUE THREAD

**Issue by reincornator** [OleksiyPenkov/MyHomeLib#3]
Приветствую. Как справиться с "иероглифовами" в некоторых местах приложения? В частности с тем, что на рисунке. Так же есть еще несколько в разных "настройках". Система W7. Спасибо.  
![Снимок экрана от 2019-10-20 22-22-38](https://user-images.githubusercontent.com/38689281/67165109-d0c2b080-f389-11e9-8e40-fa4ba1eeaf5e.png)

**Comment by SlalomJohn** [comment]
ИМХО - т.к. Win7 уже все, то для нее скорее всего никто ничего делать не будет. Если же проблема сохраняется в W10 - тогда таки да, возможно кто-то займется.

**Comment by Weegley** [comment]
На 11 то же самое. Не очень то и UTF она... Жаль - проект, похоже, заброшен...

**Comment by OleksiyPenkov** [comment]
Win 11 Eng не воспроизводится.

**Comment by SlalomJohn** [comment]
> Win 11 Eng не воспроизводится.

Еще бы. Винда 10 и 11 на UTF живут жеж...

**Comment by OleksiyPenkov** [comment]
Пересобрал в новых Дельфях, кому актуально в Вин 7, пусть проверяют. Мне негде

**Comment by SlalomJohn** [comment]
Вай! Вот за это спасибки )))
Правда не знаю - был ли смысл?

**Comment by OleksiyPenkov** [comment]
Я там еще кое-что поправил.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by OleksiyPenkov** [comment]
> Вай! Вот за это спасибки ))) Правда не знаю - был ли смысл?

Есть идея насчёт ускоренного обновления базы.

**Comment by SlalomJohn** [comment]
Плохо чтоли? Хорошо ведь!
