### ISSUE TITLE
issue with export to .mobi for Kindle

### ISSUE THREAD

**Issue by zlev-intel** [OleksiyPenkov/MyHomeLib#36]
Hi, I used one of the old versions (few years ago) and succeeded to export books to Kindle with fb2mobi script. After I trying to update to new version, script is not working, my small debugging (on script level) shows that files are not put to temp directory and conversion process cannot find the input file.
Is there something changed in export? Is there any other converter/process to use?

**Comment by OleksiyPenkov** [comment]
Well... I tested it again, and it works. So, I can't confirm the bug at this moment.
The app uses that TMP folder for conversion:
c:\Users\%Current User%\AppData\Local\Temp\_myhomelib\
