### ISSUE TITLE
Ручное обновление колелкции 2.4

### ISSUE THREAD

**Issue by Aleksei29** [OleksiyPenkov/MyHomeLib#37]
Установил версию 2.4 и перестало работать ручное обновление коллекции. Пишет "Нет доступных обновлений" хотя librusec_local_fb2.zip лежит в папке update. В настройках пробовал и полный путь и только update указывать. В 2.3 все работает, не подскажете где туплю?
![изображение](https://github.com/OleksiyPenkov/MyHomeLib/assets/141656449/218b306e-01b1-43ba-aaf3-ba616bfca856)

**Comment by OleksiyPenkov** [comment]
"Папка с обновлениями" - либо оставить поле пустым, либо указать полный путь

**Comment by OleksiyPenkov** [comment]
Поле "Папка с обновлениями" оставить пустым. librusec_local_fb2.zip положить рядом с MyHomeLib.exe

**Comment by Aleksei29** [comment]
Не помогло.
Я отписался в теме
  
>Вторник, 8 августа 2023, 9:56 +03:00 от Oleksiy Penkov ***@***.***>:
> 
> 
>Поле "Папка с обновлениями" оставить пустым. librusec_local_fb2.zip положить рядом с MyHomeLib.exe
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <OleksiyPenkov/MyHomeLib/issues/37/1669014791 @ github . com> 
 
 
--
Алексей Крисанов
Отправлено из Почты  Mail.ru

**Comment by OleksiyPenkov** [comment]
В версии [2.4.0.855](https://github.com/OleksiyPenkov/MyHomeLib/tree/2.4.0.855) работает. Обновитесь.

**Comment by Aleksei29** [comment]
Я не против обновиться, вот только как?
В ссылке исходники, мне их компилить не на чем. У меня стоит версия 2.4.0.851 в ней если делю провреить обновления пишет 
![изображение](https://github.com/OleksiyPenkov/MyHomeLib/assets/141656449/215bed2a-5181-4176-8be8-381259fdba49)

я не программист, я пользовталеь

**Comment by OleksiyPenkov** [comment]
https://github.com/OleksiyPenkov/MyHomeLib/releases/tag/2.4.0.855

**Comment by Aleksei29** [comment]
Поставил, все равно не помогло. Может потому что коллекция уже обновлена. В 2.3 он всегда обновлял, даже несколько раз одно и то же

**Comment by OleksiyPenkov** [comment]
Странно. Если файл обновления есть, то коллекция обновляется принудительно. А закиньте сюда ваш файлик collections.ini

**Comment by Aleksei29** [comment]
[collections.zip](https://github.com/OleksiyPenkov/MyHomeLib/files/12319066/collections.zip)

**Comment by Aleksei29** [comment]
Я кажется понял. надо закидывать  librusec_local_fb2.zip не в папку с MyHomeLib.exe, а туда где collections.ini
Дело в том, что этот файл находится в папке Меня как пользователя. Не знаю почему он там прописывается. Я нигде этот путь не указывал

**Comment by OleksiyPenkov** [comment]
Посмотрю
