### ISSUE TITLE
"Слетает" выбор языка каждый раз при поиске новой книги

### ISSUE THREAD

**Issue by Katran-399A** [OleksiyPenkov/MyHomeLib#4]
Прошу сделать сделать так, чтобы в MyHomeLib показывались книги ТОЛЬКО на конкретно выбранном одном языке (русском в моем случае), т.е. чтобы русский язык в окне выбора языков был жестко зафиксирован и **не "слетал" каждый раз в процессе поиска новых книг** (проблема старая).

**Comment by OleksiyPenkov** [comment]
Мы руководствовались другой логикой. Список языков формируется для каждого автора, у кого-то книг на русском может и не быть.

**Comment by OleksiyPenkov** [comment]
Можно немного подробнее объяснить? Речь идёт про панель поиска или списки книг в авторах/сериях/жанрах?
