### ISSUE TITLE
Не отправляет книгу на устройство в форматах .mobi и .epub

### ISSUE THREAD

**Issue by confeden** [OleksiyPenkov/MyHomeLib#40]
При попытке сохранить в других форматах - всё получается, но MOBI и EPUB никак не записываются. Для чтения на устройствах Kindle с недавнего времени все книги приходится экспортировать только в формате .epub - приходится пользоваться конвертером отдельным.

**Comment by OleksiyPenkov** [comment]
У нас нет встроенного конвертера для MOBI и EPUB, их нужно подключать. В справке написано как.
