### ISSUE TITLE
Чи можливо додати Автора з метаданних, а не з назви файлу?

### ISSUE THREAD

**Issue by Ga1dz1** [OleksiyPenkov/MyHomeLib#45]
![image](https://github.com/OleksiyPenkov/MyHomeLib/assets/119265705/ea254811-35b5-4b63-83e8-fa1881ed930b)
Маю невеличку бібліотеку англійських книжок, та при експорті та пошуку - інша, непотрібна мова. Чи є можливість виправити це неподобство? Пробував імпортувати у Calibre, там все норм, одначе хотілося б і тут мати можливість використовувати неймінг з мета.

**Comment by OleksiyPenkov** [comment]
Якщо б воно бралося з імені файла, перейменування вирішило б проблему. Але ж...
Додайте ваш файл сюди, я подивлюсь.

**Comment by Ga1dz1** [comment]
[Сальваторе Роберт Энтони, Dark Elf 01 - Homeland.zip](https://github.com/user-attachments/files/15879031/Dark.Elf.01.-.Homeland.zip)

**Comment by OleksiyPenkov** [comment]
MyHomeLib не вміє читати мета з epub, pdf  та інших. Тільки з fb2.
