### ISSUE TITLE
Проверка наличия обновлений

### ISSUE THREAD

**Issue by Dimon-II** [OleksiyPenkov/MyHomeLib#47]
Версия: 2.4.1.860 x64
Вместо текста отображаются теги HTML
![image](https://github.com/user-attachments/assets/61ad4b3d-36df-470c-838d-bb71c1a7c3e1)

PS И не переведено слово ВЕРСИЯ (Версія:)
![image](https://github.com/user-attachments/assets/dd813cf4-ef35-4d98-b832-8042fe52fac5)

**Comment by OleksiyPenkov** [comment]
Неправильный (нерабочий) сайт обновлений прописан в настройках. Нужно прописать https://oleksiypenkov.github.io/update/
